services:
  db:
    image: postgres:16
    container_name: bank_db_container
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5555:5432"

  backend:
    build:
      context: .
      dockerfile: bank/Dockerfile
    container_name: bank_backend
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - ExternalPayments__FedNowApiUrl=http://host.docker.internal:8770
      - ExternalPayments__RtpApiUrl=http://host.docker.internal:8000
      - ExternalPayments__SwiftApiUrl=http://host.docker.internal:3000/api/v1/swift/message
      - ExternalPayments__AchApiUrl=http://host.docker.internal:8310
      - ExternalPayments__AchSftpHost=host.docker.internal
      - Klik__ApiUrl=http://host.docker.internal:8001
      - Klik__ApiKey=klik_RbKGXOZH7gXAwr-soCdei96lQXvfWy7XewpPRgsCqPQ
      - Klik__Zone=US
      - Klik__BankName=AMERICAN_BANK
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    volumes:
      - ./bank/Keys:/app/Keys

  # Frontend React wyłączony – UI jest teraz serwowany przez Blazor w kontenerze backendu
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: bank_frontend
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   depends_on:
  #     - backend